import type { Locale } from "@/lib/i18n/config";
import type {
  ModerationPriority,
  ModerationStatus,
  ReportReason,
  ReportStatus,
  ReportTargetType,
} from "@/lib/moderation";

export function getModerationCopy(locale: Locale) {
  if (locale === "uk") {
    return {
      dashboard: {
        eyebrow: "Модерація",
        title: "Черга перевірки контенту",
        description:
          "Скарги на профілі, роботи, статті, опитування, коментарі, сторінки компаній і вакансії — з поточним статусом і діями. Кожне рішення потрапляє в журнал, а власник отримує сповіщення.",
        openQueue: "Відкрити модерацію",
        noAccess: "Ця сторінка доступна лише адміністраторам.",
        empty: "У черзі немає активних скарг.",
        reportsCount: "Активні скарги",
        urgentCount: "Термінові",
        profilesCount: "На профілі",
        projectsCount: "На проєкти",
        reportDetails: "Деталі скарги",
        targetStatus: "Статус контенту",
        reportStatus: "Статус скарги",
        reportReason: "Причина",
        reporter: "Хто поскаржився",
        createdAt: "Створено",
        targetOwner: "Власник контенту",
        resolutionNote: "Нотатка модератора",
        openTarget: "Відкрити сторінку",
        reviewActions: "Дії модерації",
      },
      report: {
        buttonProject: "Поскаржитися на проєкт",
        buttonProfile: "Поскаржитися на профіль",
        buttonCompany: "Поскаржитися на сторінку",
        buttonVacancy: "Поскаржитися на вакансію",
        buttonArticle: "Поскаржитися на статтю",
        buttonPoll: "Поскаржитися на опитування",
        buttonComment: "Поскаржитися",
        titleProject: "Скарга на проєкт",
        titleProfile: "Скарга на профіль",
        titleCompany: "Скарга на сторінку компанії",
        titleVacancy: "Скарга на вакансію",
        titleArticle: "Скарга на статтю",
        titlePoll: "Скарга на опитування",
        titleComment: "Скарга на коментар",
        description:
          "Опишіть проблему коротко й по суті. Це допоможе швидше пріоритезувати перевірку.",
        reasonLabel: "Причина скарги",
        detailsLabel: "Деталі",
        detailsPlaceholder:
          "Додайте контекст: що саме порушує правила, де це видно і чому потрібна перевірка.",
        submit: "Надіслати скаргу",
        sending: "Надсилання...",
        close: "Закрити",
        cancel: "Скасувати",
        success: "Скаргу прийнято. Вона з'явилася в черзі модерації.",
        duplicate:
          "Схожа активна скарга від вас уже є. Не потрібно дублювати її ще раз.",
        errorFallback: "Не вдалося надіслати скаргу.",
        rateLimited: "Забагато скарг за хвилину. Спробуйте трохи пізніше.",
        loginToReport: "Увійдіть, щоб поскаржитися",
      },
      actions: {
        notePlaceholder:
          "Коротка службова примітка: що знайшли, чому змінюєте статус, що ще потрібно перевірити.",
        saveApprove: "Підтвердити як нормальний",
        saveReview: "Перенести на перевірку",
        saveRestrict: "Обмежити показ",
        saveRemove: "Прибрати з публічного доступу",
        removeComment: "Видалити коментар",
        keepComment: "Залишити коментар",
        dismissReport: "Відхилити скаргу",
        resolveReport: "Закрити скаргу",
        saving: "Збереження...",
        success: "Дію застосовано.",
        errorFallback: "Не вдалося оновити модерацію.",
      },
      statusLabels: {
        approved: "Схвалено",
        under_review: "На перевірці",
        restricted: "Обмежено",
        removed: "Прибрано",
      } satisfies Record<ModerationStatus, string>,
      reportStatusLabels: {
        open: "Відкрита",
        triaged: "В роботі",
        resolved: "Закрита",
        dismissed: "Відхилена",
      } satisfies Record<ReportStatus, string>,
      reasonLabels: {
        copyright_infringement: "Порушення авторських прав",
        inappropriate_content: "Неприйнятний контент",
        harmful_or_dangerous: "Шкідливий або небезпечний контент",
        sexual_content: "Сексуальний контент",
        harassment_or_hate: "Переслідування, ненависть або образи",
        spam_or_scam: "Спам або шахрайство",
        impersonation: "Видавання себе за іншу особу",
        other: "Інша причина",
      } satisfies Record<ReportReason, string>,
      priorityLabels: {
        normal: "Звичайний",
        high: "Високий",
        urgent: "Терміновий",
      } satisfies Record<ModerationPriority, string>,
      targetLabels: {
        profile: "Профіль",
        project: "Проєкт",
        article: "Стаття",
        poll: "Опитування",
        company: "Компанія",
        vacancy: "Вакансія",
        project_comment: "Коментар до проєкту",
        article_comment: "Коментар до статті",
        poll_comment: "Коментар до опитування",
      } satisfies Record<ReportTargetType, string>,
    };
  }

  return {
    dashboard: {
      eyebrow: "Moderation",
      title: "Content review queue",
      description:
        "Reports on profiles, projects, articles, polls, comments, company pages and vacancies — with the current status and actions. Every decision goes into the log, and the owner is notified.",
      openQueue: "Open moderation",
      noAccess: "This page is available only to administrators.",
      empty: "There are no active reports in the queue.",
      reportsCount: "Active reports",
      urgentCount: "Urgent",
      profilesCount: "Against profiles",
      projectsCount: "Against projects",
      reportDetails: "Report details",
      targetStatus: "Content status",
      reportStatus: "Report status",
      reportReason: "Reason",
      reporter: "Reporter",
      createdAt: "Created",
      targetOwner: "Content owner",
      resolutionNote: "Moderator note",
      openTarget: "Open page",
      reviewActions: "Moderation actions",
    },
    report: {
      buttonProject: "Report project",
      buttonProfile: "Report profile",
      buttonCompany: "Report page",
      buttonVacancy: "Report vacancy",
      buttonArticle: "Report article",
      buttonPoll: "Report poll",
      buttonComment: "Report",
      titleProject: "Report project",
      titleProfile: "Report profile",
      titleCompany: "Report company page",
      titleVacancy: "Report vacancy",
      titleArticle: "Report article",
      titlePoll: "Report poll",
      titleComment: "Report comment",
      description:
        "Describe the issue clearly and briefly. That makes prioritization and review much easier.",
      reasonLabel: "Report reason",
      detailsLabel: "Details",
      detailsPlaceholder:
        "Add useful context: what is wrong, where it appears, and why it should be reviewed.",
      submit: "Send report",
      sending: "Sending...",
      close: "Close",
      cancel: "Cancel",
      success: "Report submitted. It is now in the moderation queue.",
      duplicate:
        "You already have a similar active report for this item. No need to submit it again.",
      errorFallback: "Could not submit the report.",
      rateLimited: "Too many reports in a minute. Try again a bit later.",
      loginToReport: "Log in to report",
    },
    actions: {
      notePlaceholder:
        "Short internal note: what was found, why the status changes, and what still needs review.",
      saveApprove: "Mark as approved",
      saveReview: "Move to review",
      saveRestrict: "Restrict visibility",
      saveRemove: "Remove from public access",
      removeComment: "Delete the comment",
      keepComment: "Keep the comment",
      dismissReport: "Dismiss report",
      resolveReport: "Resolve report",
      saving: "Saving...",
      success: "Moderation action applied.",
      errorFallback: "Could not update moderation.",
    },
    statusLabels: {
      approved: "Approved",
      under_review: "Under review",
      restricted: "Restricted",
      removed: "Removed",
    } satisfies Record<ModerationStatus, string>,
    reportStatusLabels: {
      open: "Open",
      triaged: "Triaged",
      resolved: "Resolved",
      dismissed: "Dismissed",
    } satisfies Record<ReportStatus, string>,
    reasonLabels: {
      copyright_infringement: "Copyright infringement",
      inappropriate_content: "Inappropriate content",
      harmful_or_dangerous: "Harmful or dangerous content",
      sexual_content: "Sexual content",
      harassment_or_hate: "Harassment, hate, or abuse",
      spam_or_scam: "Spam or scam",
      impersonation: "Impersonation",
      other: "Other",
    } satisfies Record<ReportReason, string>,
    priorityLabels: {
      normal: "Normal",
      high: "High",
      urgent: "Urgent",
    } satisfies Record<ModerationPriority, string>,
    targetLabels: {
      profile: "Profile",
      project: "Project",
      article: "Article",
      poll: "Poll",
      company: "Company",
      vacancy: "Vacancy",
      project_comment: "Project comment",
      article_comment: "Article comment",
      poll_comment: "Poll comment",
    } satisfies Record<ReportTargetType, string>,
  };
}

export type ModerationCopy = ReturnType<typeof getModerationCopy>;
