/**
 * Regenerate the self-hosted webfonts in src/app/fonts/ and the @font-face
 * stylesheet src/app/fonts.css.
 *
 * The fonts used to come from next/font/google, which fetches them from Google on
 * every build. Turbopack does not retry that fetch, so one slow response failed
 * the whole production build with "Can't resolve
 * '@vercel/turbopack-next/internal/font/google/font'". Fetching them once, here,
 * keeps the build offline and deterministic.
 *
 * What it writes is byte-for-byte what next/font/google was serving: the same
 * woff2 subset files, the same unicode-ranges, and the same metric-adjusted
 * fallback faces (taken from Next's own metrics database, so CLS behaviour is
 * unchanged).
 *
 * Run: node scripts/refresh-fonts.mjs
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { calculateSizeAdjustValues } from "next/dist/server/font-utils.js";

// A browser UA is required, or Google serves legacy .ttf instead of .woff2.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

/**
 * The families the app uses, with the weight range and the CSS variable each one
 * backs. All three are variable fonts, so Google serves ONE file per subset that
 * covers every weight in the range — verified by requesting the weights as a list
 * and as a range and comparing the returned file sets.
 */
const FAMILIES = [
  {
    family: "Literata",
    slug: "literata",
    variable: "--font-display",
    weight: [400, 700],
  },
  {
    family: "Manrope",
    slug: "manrope",
    variable: "--font-body",
    weight: [400, 700],
  },
  {
    family: "JetBrains Mono",
    slug: "jetbrains-mono",
    variable: "--font-mono",
    weight: [400, 500],
  },
];

// Kept in step with what the old next/font/google calls requested. Everything
// else Google offers (greek, vietnamese, cyrillic-ext, …) is left out.
const SUBSETS = ["latin", "latin-ext", "cyrillic"];

const FONT_DIR = path.resolve("src/app/fonts");
const CSS_PATH = path.resolve("src/app/fonts.css");

async function fetchGoogle(url) {
  const res = await fetch(url, { headers: { "user-agent": UA } });
  if (!res.ok) {
    throw new Error(`${res.status} ${res.statusText} — ${url}`);
  }
  return res;
}

function cssUrl({ family, weight }) {
  const name = encodeURIComponent(family).replace(/%20/g, "+");
  return `https://fonts.googleapis.com/css2?family=${name}:wght@${weight[0]}..${weight[1]}&display=swap`;
}

/** Split Google's stylesheet into { subset, url, unicodeRange } faces. */
function parseFaces(css) {
  const faces = [];
  for (const block of css.split("/*").slice(1)) {
    const subset = block.slice(0, block.indexOf("*/")).trim();
    const url = /src:\s*url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    if (url && unicodeRange) {
      faces.push({ subset, url, unicodeRange });
    }
  }
  return faces;
}

const lines = [
  "/*",
  " * GENERATED by scripts/refresh-fonts.mjs — do not edit by hand.",
  " *",
  " * Self-hosted webfonts: the same woff2 subset files, unicode-ranges and",
  " * metric-adjusted fallbacks that next/font/google used to fetch from Google on",
  " * every build. They live in the repo because that fetch is a single point of",
  " * failure — Turbopack does not retry it, and one slow response failed the whole",
  ' * production build with "Can\'t resolve',
  " * '@vercel/turbopack-next/internal/font/google/font'\".",
  " *",
  " * The url()s are bundler-processed, so the files are emitted with a content hash",
  " * and served immutable, exactly as they were before.",
  " */",
  "",
];

const downloads = new Map(); // remote url → local file name
const variables = [];

for (const entry of FAMILIES) {
  const css = await (await fetchGoogle(cssUrl(entry))).text();
  const faces = parseFaces(css);

  lines.push(`/* ${entry.family} — ${entry.variable} */`);
  for (const subset of SUBSETS) {
    const face = faces.find((candidate) => candidate.subset === subset);
    if (!face) {
      throw new Error(`${entry.family}: Google served no "${subset}" subset`);
    }
    const name = `${entry.slug}-${subset}.woff2`;
    downloads.set(face.url, name);
    lines.push(
      "@font-face {",
      `  font-family: "${entry.family}";`,
      "  font-style: normal;",
      `  font-weight: ${entry.weight[0]} ${entry.weight[1]};`,
      "  font-display: swap;",
      `  src: url("./fonts/${name}") format("woff2");`,
      `  unicode-range: ${face.unicodeRange};`,
      "}",
    );
  }
  lines.push("");

  // Next's own numbers, derived from its bundled Google Fonts metrics, so the
  // system font the browser paints first occupies the same space as the webfont.
  const { ascent, descent, lineGap, fallbackFont, sizeAdjust } =
    calculateSizeAdjustValues(entry.family);
  const fallbackName = `${entry.family} Fallback`;
  lines.push(
    `@font-face {`,
    `  font-family: "${fallbackName}";`,
    `  src: local("${fallbackFont}");`,
    `  ascent-override: ${ascent}%;`,
    `  descent-override: ${descent}%;`,
    `  line-gap-override: ${lineGap}%;`,
    `  size-adjust: ${sizeAdjust}%;`,
    "}",
    "",
  );
  variables.push(`  ${entry.variable}: "${entry.family}", "${fallbackName}";`);
}

lines.push(
  "/* Everything in the app reaches the families through these variables. */",
  ":root {",
  ...variables,
  "}",
  "",
);

// Rewrite the directory from scratch so a renamed or dropped subset cannot leave
// an orphaned file behind that nothing references.
await rm(FONT_DIR, { recursive: true, force: true });
await mkdir(FONT_DIR, { recursive: true });

let bytes = 0;
for (const [url, name] of downloads) {
  const buffer = Buffer.from(await (await fetchGoogle(url)).arrayBuffer());
  bytes += buffer.byteLength;
  await writeFile(path.join(FONT_DIR, name), buffer);
}
await writeFile(CSS_PATH, lines.join("\n"), "utf8");

const written = (await readdir(FONT_DIR)).length;
console.log(
  `fonts.css + ${written} woff2 files (${(bytes / 1024).toFixed(0)} KB) written`,
);
